# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editinputmember.ui'
#
# Created: Fri Feb  5 13:58:42 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_InputDialog(object):
    def setupUi(self, InputDialog):
        InputDialog.setObjectName(_fromUtf8("InputDialog"))
        InputDialog.resize(450, 250)
        InputDialog.setMaximumSize(QtCore.QSize(500, 250))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        InputDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/area.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        InputDialog.setWindowIcon(icon)
        InputDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.vboxlayout = QtGui.QVBoxLayout(InputDialog)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(9)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.label_2 = QtGui.QLabel(InputDialog)
        self.label_2.setMinimumSize(QtCore.QSize(80, 30))
        self.label_2.setMaximumSize(QtCore.QSize(80, 30))
        self.label_2.setText(_fromUtf8("Type"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridlayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.typComboBox = QtGui.QComboBox(InputDialog)
        self.typComboBox.setMinimumSize(QtCore.QSize(150, 30))
        self.typComboBox.setMaximumSize(QtCore.QSize(150, 30))
        self.typComboBox.setObjectName(_fromUtf8("typComboBox"))
        self.gridlayout.addWidget(self.typComboBox, 1, 1, 1, 1)
        self.label = QtGui.QLabel(InputDialog)
        self.label.setMinimumSize(QtCore.QSize(80, 30))
        self.label.setMaximumSize(QtCore.QSize(80, 30))
        self.label.setText(_fromUtf8("Name"))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.nameLE = QtGui.QLineEdit(InputDialog)
        self.nameLE.setMinimumSize(QtCore.QSize(150, 30))
        self.nameLE.setMaximumSize(QtCore.QSize(150, 30))
        self.nameLE.setObjectName(_fromUtf8("nameLE"))
        self.gridlayout.addWidget(self.nameLE, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 0, 2, 2, 1)
        self.vboxlayout.addLayout(self.gridlayout)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.label_3 = QtGui.QLabel(InputDialog)
        self.label_3.setMinimumSize(QtCore.QSize(80, 30))
        self.label_3.setMaximumSize(QtCore.QSize(80, 30))
        self.label_3.setText(_fromUtf8("Range"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.vboxlayout1.addWidget(self.label_3)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.vboxlayout1.addItem(spacerItem1)
        self.hboxlayout.addLayout(self.vboxlayout1)
        self.gridlayout1 = QtGui.QGridLayout()
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.p1LE = QtGui.QLineEdit(InputDialog)
        self.p1LE.setEnabled(False)
        self.p1LE.setMinimumSize(QtCore.QSize(60, 30))
        self.p1LE.setMaximumSize(QtCore.QSize(100, 30))
        self.p1LE.setObjectName(_fromUtf8("p1LE"))
        self.gridlayout1.addWidget(self.p1LE, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(InputDialog)
        self.label_4.setMinimumSize(QtCore.QSize(60, 20))
        self.label_4.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridlayout1.addWidget(self.label_4, 1, 0, 1, 1)
        self.p2LE = QtGui.QLineEdit(InputDialog)
        self.p2LE.setEnabled(False)
        self.p2LE.setMinimumSize(QtCore.QSize(60, 30))
        self.p2LE.setMaximumSize(QtCore.QSize(100, 30))
        self.p2LE.setObjectName(_fromUtf8("p2LE"))
        self.gridlayout1.addWidget(self.p2LE, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(InputDialog)
        self.label_5.setMinimumSize(QtCore.QSize(60, 20))
        self.label_5.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridlayout1.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(InputDialog)
        self.label_7.setMinimumSize(QtCore.QSize(60, 20))
        self.label_7.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridlayout1.addWidget(self.label_7, 1, 3, 1, 1)
        self.label_6 = QtGui.QLabel(InputDialog)
        self.label_6.setMinimumSize(QtCore.QSize(60, 20))
        self.label_6.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridlayout1.addWidget(self.label_6, 1, 2, 1, 1)
        self.p4LE = QtGui.QLineEdit(InputDialog)
        self.p4LE.setEnabled(False)
        self.p4LE.setMinimumSize(QtCore.QSize(60, 30))
        self.p4LE.setMaximumSize(QtCore.QSize(100, 30))
        self.p4LE.setObjectName(_fromUtf8("p4LE"))
        self.gridlayout1.addWidget(self.p4LE, 0, 3, 1, 1)
        self.p3LE = QtGui.QLineEdit(InputDialog)
        self.p3LE.setEnabled(False)
        self.p3LE.setMinimumSize(QtCore.QSize(60, 30))
        self.p3LE.setMaximumSize(QtCore.QSize(100, 30))
        self.p3LE.setObjectName(_fromUtf8("p3LE"))
        self.gridlayout1.addWidget(self.p3LE, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem2, 0, 4, 1, 1)
        self.hboxlayout.addLayout(self.gridlayout1)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem3)
        self.label_8 = QtGui.QLabel(InputDialog)
        self.label_8.setMinimumSize(QtCore.QSize(106, 65))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8("icons/trapezklein.png")))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.hboxlayout1.addWidget(self.label_8)
        spacerItem4 = QtGui.QSpacerItem(16, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem4)
        self.gridlayout2 = QtGui.QGridLayout()
        self.gridlayout2.setMargin(0)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        spacerItem5 = QtGui.QSpacerItem(20, 21, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout2.addItem(spacerItem5, 0, 0, 1, 1)
        self.okButton = QtGui.QPushButton(InputDialog)
        self.okButton.setMinimumSize(QtCore.QSize(100, 30))
        self.okButton.setMaximumSize(QtCore.QSize(100, 30))
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.gridlayout2.addWidget(self.okButton, 1, 0, 1, 1)
        self.cancelButton = QtGui.QPushButton(InputDialog)
        self.cancelButton.setMinimumSize(QtCore.QSize(100, 30))
        self.cancelButton.setMaximumSize(QtCore.QSize(100, 30))
        self.cancelButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cancelButton.setText(_fromUtf8("Cancel"))
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.gridlayout2.addWidget(self.cancelButton, 1, 1, 1, 1)
        self.hboxlayout1.addLayout(self.gridlayout2)
        self.vboxlayout.addLayout(self.hboxlayout1)

        self.retranslateUi(InputDialog)
        self.typComboBox.setCurrentIndex(-1)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), InputDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(InputDialog)
        InputDialog.setTabOrder(self.nameLE, self.typComboBox)
        InputDialog.setTabOrder(self.typComboBox, self.p1LE)
        InputDialog.setTabOrder(self.p1LE, self.p2LE)
        InputDialog.setTabOrder(self.p2LE, self.p3LE)
        InputDialog.setTabOrder(self.p3LE, self.p4LE)
        InputDialog.setTabOrder(self.p4LE, self.okButton)
        InputDialog.setTabOrder(self.okButton, self.cancelButton)

    def retranslateUi(self, InputDialog):
        InputDialog.setWindowTitle(_translate("InputDialog", "Edit Input Membership Function", None))
        self.label_4.setText(_translate("InputDialog", "p1", None))
        self.label_5.setText(_translate("InputDialog", "p2", None))
        self.label_7.setText(_translate("InputDialog", "p4", None))
        self.label_6.setText(_translate("InputDialog", "p3", None))
        self.okButton.setText(_translate("InputDialog", "OK", None))


